### PR TITLE
Some hints for getting started

### PR DESCRIPTION
**Pull request by paines**
Raylib need to be compiled using fPIC and exmaples getting compiled and run, needs some hackery.

### CODE REVIEW

**Comment by yashrk** [comment]
Hi. Thank you for your pull request and for the attention to my project. Can you explain you proposal a bit more in detail?

I tested examples raylib-scm on many computers and never need to do tricks with `LD_PRELOAD`.

I'm afraid I just didn't get your point yet. Why `-fPIC` is a problem? This compilation option is obligatory for shared libraries.

**Comment by paines** [comment]
Hey, thanks for coming back to me. Also thank for the bindings. 

So, after compiling raylib and then your bindings, I got linking errors during chicken-install  which could be resolved by reompiling raylib with -fPIC.

And for the examples I will get , e.g. :
INFO: Initializing raylib 3.0
./sound_loading: symbol lookup error: /var/lib//chicken/8/raylib-scm.so: undefined symbol: XInitThreads

The XinitThreads symbol is missing, which can be remedied with the preload.

Strange that you have a different behaviour.

**Comment by yashrk** [comment]
It's very interesting.

Did you compiled raylib as a shared library or as an static `.a` file? If you raylib is a shared library, can you show me the output of `ldd libraylib.so`?

What version of Chicken you use?

I can't reproduce this just now, but I'll try to research this bug ASAP.

**Comment by paines** [comment]
I just pulled raylibs git repo and it compiled a static lib by default. I will try to build a shared one, and see if the behaviour changes. chicken is 4.12.0, default from Ubuntu 18.04.

**Comment by paines** [comment]
Yeah, the whole problem is because of static vs shared raylib. With a shared no LD_PRELOAD or -fPIC hackery is needed. I will close the merge reqeust. Sorry for the noise!

**Pull request closed without merging**
